# Generated by Django 6.0.2 on 2026-02-17 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('DOG', 'Perro'), ('CAT', 'Gato')], max_length=10)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, max_length=100)),
                ('size', models.CharField(choices=[('SMALL', 'Pequeño'), ('MEDIUM', 'Mediano'), ('LARGE', 'Grande')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen alojada externamente', max_length=500, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('ADOPTED', 'Adoptado')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
